apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample
  description: Sample description.
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: bangalore
